### ISSUE TITLE
Create channel Magento integration issue: Widget content loading failed

### ISSUE THREAD

**Issue by maurisource** [orocrm/platform#219]
![screen shot 2015-01-27 at 1 45 26 pm](https://cloud.githubusercontent.com/assets/1178609/5924554/cd111b54-a62a-11e4-9323-7436415bc251.png)
HI, on a fresh install of OroCRM I'm trying to create a new connection channel to Magento. After following the guide to do so and switching dropdown to Magento; I'm stuck on "Configure Integration". Once clicked the popup of "configure integration" opens shows this error message: "Widget content loading failed"

I searched for this issue everywhere and no one mentioned it before. 
@alsma-magecore Could you please provide a solution or what have I missed ?

**Comment by rgrebenchuk** [comment]
Hi @maurisource 
Could you please provide more details? We need to know version of OroCRM you installed and errors from php and application logs. And we will try to find solution

**Comment by maurisource** [comment]
Hi @rgrebenchuk thanks for getting back. We are using latest versions 1.6.0

[Tue Jan 27 12:05:40.791388 2015] [:error] [pid 26855] [client 137.175.202.235:49792] PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'The given 'driver' mysql -u root is unknown, Doctrine currently supports only the following drivers: pdo_mysql, pdo_sqlite, pdo_pgsql, pdo_oci, oci8, ibm_db2, pdo_ibm, pdo_sqlsrv, mysqli, drizzle_pdo_mysql, sqlsrv' in /var/www/html/crm-application/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:72\nStack trace:\n#0 /var/www/html/crm-application/vendor/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(180): Doctrine\\DBAL\\DBALException::unknownDriver('mysql -u root', Array)\n#1 /var/www/html/crm-application/vendor/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(136): Doctrine\\DBAL\\DriverManager::_checkParams(Array)\n#2 /var/www/html/crm-application/vendor/doctrine/doctrine-bundle/Doctrine/Bundle/DoctrineBundle/ConnectionFactory.php(58): Doctrine\\DBAL\\DriverManager::getConnection(Array, Object(Doctrine\\DBAL\\Configuration), Object(Oro\\Bundle\\EntityBundle\\Event\\OroEventManager))\n#3 /var/www/html/crm-application/app/cache/prod/appProdProjectConta in /var/www/html/crm-application/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php on line 72, referer: http://167.114.68.201/crm-application/web/install.php
[Tue Jan 27 12:07:49.242602 2015] [:error] [pid 24538] [client 137.175.202.235:49805] PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'The given 'driver' mysql -u root is unknown, Doctrine currently supports only the following drivers: pdo_mysql, pdo_sqlite, pdo_pgsql, pdo_oci, oci8, ibm_db2, pdo_ibm, pdo_sqlsrv, mysqli, drizzle_pdo_mysql, sqlsrv' in /var/www/html/crm-application/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:72\nStack trace:\n#0 /var/www/html/crm-application/vendor/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(180): Doctrine\\DBAL\\DBALException::unknownDriver('mysql -u root', Array)\n#1 /var/www/html/crm-application/vendor/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(136): Doctrine\\DBAL\\DriverManager::_checkParams(Array)\n#2 /var/www/html/crm-application/vendor/doctrine/doctrine-bundle/Doctrine/Bundle/DoctrineBundle/ConnectionFactory.php(58): Doctrine\\DBAL\\DriverManager::getConnection(Array, Object(Doctrine\\DBAL\\Configuration), Object(Oro\\Bundle\\EntityBundle\\Event\\OroEventManager))\n#3 /var/www/html/crm-application/app/cache/prod/appProdProjectConta in /var/www/html/crm-application/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php on line 72
[2015-01-27 13:12:52] request.INFO: Matched route "index" (parameters: "_controller": "Oro\Bundle\DistributionBundle\Controller\PackageController::listInstalledAction", "_route": "index") [] []
[2015-01-27 13:12:52] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2015-01-27 13:12:52] security.DEBUG: Access is denied (user is not fully authenticated) by "/var/www/html/crm-application/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php" at line 70; redirecting to authentication entry point [] []
[2015-01-27 13:12:52] security.DEBUG: Calling Authentication entry point [] []
[2015-01-27 13:12:52] security.DEBUG: Write SecurityContext in the session [] []
[2015-01-27 13:12:53] request.INFO: Matched route "oro_distribution_security_login" (parameters: "_controller": "Oro\Bundle\DistributionBundle\Controller\SecurityController::loginAction", "_route": "oro_distribution_security_login") [] []
[2015-01-27 13:12:56] request.INFO: Matched route "oro_distribution_security_login_check" (parameters: "_route": "oro_distribution_security_login_check") [] []
[2015-01-27 13:12:56] security.INFO: User "maurisource" has been authenticated successfully [] []
[2015-01-27 13:12:56] security.DEBUG: Clearing remember-me cookie "BAPRM_DIST" [] []
[2015-01-27 13:12:56] security.DEBUG: Did not send remember-me cookie (remember-me parameter "_remember_me" was not sent). [] []
[2015-01-27 13:12:56] security.DEBUG: Remember-me was not requested. [] []
[2015-01-27 13:12:56] security.DEBUG: Write SecurityContext in the session [] []
[2015-01-27 13:12:56] request.INFO: Matched route "oro_distribution_package_listinstalled" (parameters: "_controller": "Oro\Bundle\DistributionBundle\Controller\PackageController::listInstalledAction", "_route": "oro_distribution_package_listinstalled") [] []
[2015-01-27 13:12:56] security.DEBUG: Read SecurityContext from the session [] []
[2015-01-27 13:12:56] security.DEBUG: Reloading user from user provider. [] []
[2015-01-27 13:12:56] security.DEBUG: Username "maurisource" was reloaded from user provider. [] []
[2015-01-27 13:13:07] security.DEBUG: Write SecurityContext in the session [] []
[2015-01-27 13:14:45] request.INFO: Matched route "oro_distribution_package_listavailable" (parameters: "_controller": "Oro\Bundle\DistributionBundle\Controller\PackageController::listAvailableAction", "_route": "oro_distribution_package_listavailable") [] []
[2015-01-27 13:14:45] security.DEBUG: Read SecurityContext from the session [] []
[2015-01-27 13:14:45] security.DEBUG: Reloading user from user provider. [] []
[2015-01-27 13:14:45] security.DEBUG: Username "maurisource" was reloaded from user provider. [] []
[2015-01-27 13:14:52] security.DEBUG: Write SecurityContext in the session [] []
[2015-01-27 13:27:59] request.INFO: Matched route "index" (parameters: "_controller": "Oro\Bundle\DistributionBundle\Controller\PackageController::listInstalledAction", "_route": "index") [] []
[2015-01-27 13:27:59] security.DEBUG: Read SecurityContext from the session [] []
[2015-01-27 13:27:59] security.DEBUG: Reloading user from user provider. [] []
[2015-01-27 13:27:59] security.DEBUG: Username "maurisource" was reloaded from user provider. [] []
[2015-01-27 13:28:06] security.DEBUG: Write SecurityContext in the session [] []

**Comment by maurisource** [comment]
Is this the information you were looking for?
Thanks..

**Comment by rgrebenchuk** [comment]
not sure, these errors from another place . Can you remove app/caches and logs and try again and checks for new errors and please check browser JS console?

**Comment by maurisource** [comment]
Ok browser JS console definitely lights up something's missing:

![screen shot 2015-01-28 at 1 36 20 pm](https://cloud.githubusercontent.com/assets/1178609/5944152/c27ef42c-a6f2-11e4-9e68-6db2991e0d3a.png)

**Comment by maurisource** [comment]
The requested URL /crm-application/web/channel/integration/create/magento was not found on this server.

**Comment by rgrebenchuk** [comment]
Request crm-application/web/channel/integration/create/magento should return 500
Request crm-application/web/channel/integration/create/magento?&_widgetContainer=dialog should return dialog as standalone page
If you have 404 in both cases then need to check web server rewrites

**Comment by maurisource** [comment]
Hi, thanks for that heads up. It seems fixed.
Looks like no tutorial actually insisted that mod_rewrite should be activated on server in order not to run into such errors.

For those having same issue, actually this is what I've done:

Enable mod_rewrite $ sudo a2enmod rewrite

Then add this to apache2 000-default.conf (modify the path to your crm-application /web folder)
<Directory /var/www/html/crm-application/web>
        AllowOverride All
        Order allow,deny
        allow from all
</Directory>  

run $ service apache2 restart
